/**
 * Fajita appearance for Clerk-hosted UI (SignIn, SignUp, UserButton, user
 * profile flows). We use Clerk's components for security-critical flows and
 * theme them to the Fajita token system rather than reimplementing password,
 * verification, and MFA handling. Values reference CSS variables so the
 * components follow light/dark automatically.
 *
 * Docs: docs/application/application-shell.md (auth surfaces).
 */
export const clerkAppearance = {
  elevation: "flush" as const,
  options: {
    socialButtonsVariant: "blockButton" as const,
    socialButtonsPlacement: "top" as const,
  },
  variables: {
    colorPrimary: "var(--color-text-primary)",
    colorPrimaryForeground: "var(--color-background-primary)",
    colorForeground: "var(--color-text-primary)",
    colorMutedForeground: "var(--color-text-muted)",
    colorBackground: "transparent",
    colorInput: "var(--color-background-elevated)",
    colorInputForeground: "var(--color-text-primary)",
    colorBorder: "var(--color-border-strong)",
    colorDanger: "var(--color-status-down-bold)",
    colorSuccess: "var(--color-status-operational-bold)",
    colorWarning: "var(--color-status-degraded-bold)",
    colorRing: "transparent",
    borderRadius: "0.625rem",
    spacing: "1rem",
    fontFamily: "var(--font-sans)",
    fontFamilyButtons: "var(--font-sans)",
    fontSize: "var(--text-body)",
  },
  elements: {
    rootBox: {
      width: "100%",
      maxWidth: "none",
    },
    cardBox: {
      width: "100%",
      maxWidth: "none",
      boxShadow: "none",
      border: "none",
      backgroundColor: "transparent",
      padding: 0,
    },
    scrollBox: {
      boxShadow: "none",
      border: "none",
      backgroundColor: "transparent",
      padding: 0,
    },
    pageScrollBox: {
      boxShadow: "none",
      border: "none",
      backgroundColor: "transparent",
      padding: 0,
    },
    card: {
      boxShadow: "none",
      border: "none",
      backgroundColor: "transparent",
      padding: 0,
    },
    main: {
      display: "grid",
      gap: "var(--space-5)",
      padding: 0,
    },
    header: { display: "none" },
    headerTitle: { display: "none" },
    headerSubtitle: { display: "none" },
    logoBox: { display: "none" },
    footer: { display: "none" },
    footerPages: { display: "none" },
    footerAction: { display: "none" },
    socialButtonsRoot: {
      border: "none",
      boxShadow: "none",
      padding: 0,
      margin: 0,
      backgroundColor: "transparent",
    },
    socialButtons: {
      display: "grid",
      gap: "var(--space-3)",
      width: "100%",
    },
    socialButtonsBlockButton: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "var(--space-3)",
      border: "1px solid var(--color-border-strong)",
      backgroundColor: "var(--color-background-elevated)",
      boxShadow: "none",
      fontWeight: 600,
      fontSize: "var(--text-body-sm)",
      minHeight: "3rem",
      width: "100%",
      borderRadius: "0.625rem",
      transition: "border-color 150ms ease, background-color 150ms ease",
    },
    socialButtonsBlockButtonText: {
      fontWeight: 600,
      border: "none",
      backgroundColor: "transparent",
      boxShadow: "none",
      minHeight: "auto",
      width: "auto",
      padding: 0,
    },
    dividerRow: {
      marginBlock: "var(--space-4)",
      gap: "var(--space-3)",
    },
    dividerLine: {
      backgroundColor: "var(--color-border-subtle)",
      height: "1px",
    },
    dividerText: {
      color: "var(--color-text-muted)",
      fontSize: "var(--text-caption)",
      paddingInline: "var(--space-3)",
      textTransform: "lowercase",
    },
    form: {
      display: "grid",
      gap: "var(--space-5)",
    },
    formFieldRow: {
      margin: 0,
    },
    formField: {
      display: "grid",
      gap: "var(--space-2)",
    },
    formFieldLabel: {
      fontWeight: 600,
      fontSize: "var(--text-body-sm)",
      color: "var(--color-text-primary)",
      margin: 0,
    },
    formFieldInput: {
      border: "1px solid var(--color-border-strong)",
      boxShadow: "none",
      minHeight: "3rem",
      padding: "0.75rem 1rem",
      borderRadius: "0.625rem",
      fontSize: "var(--text-body)",
      backgroundColor: "var(--color-background-elevated)",
      transition: "border-color 150ms ease, box-shadow 150ms ease",
    },
    formFieldInputShowPasswordButton: {
      color: "var(--color-text-muted)",
    },
    formFieldAction: {
      color: "var(--color-text-primary)",
      fontWeight: 500,
      fontSize: "var(--text-body-sm)",
      textDecoration: "underline",
      textDecorationColor: "var(--color-brand-ember)",
      textUnderlineOffset: "0.2em",
      textDecorationThickness: "1px",
    },
    formButtonPrimary: {
      backgroundColor: "var(--color-text-primary)",
      color: "var(--color-background-primary)",
      textTransform: "none",
      fontWeight: 600,
      fontSize: "var(--text-body-sm)",
      boxShadow: "none",
      backgroundImage: "none",
      minHeight: "3rem",
      marginTop: "var(--space-1)",
      borderRadius: "0.625rem",
      width: "100%",
      border: "none",
      transition: "background-color 150ms ease, opacity 150ms ease",
    },
    formButtonReset: {
      color: "var(--color-text-primary)",
      textDecoration: "underline",
      textDecorationColor: "var(--color-brand-ember)",
      textUnderlineOffset: "0.2em",
    },
    identityPreviewEditButton: {
      color: "var(--color-brand-ember)",
    },
    footerActionLink: { color: "var(--color-brand-ember)" },
  },
};
