import type { LaunchBlocker } from "./types";

export const LAUNCH_BLOCKERS: LaunchBlocker[] = [
  {
    id: "LB-001",
    title: "No error-monitoring / APM vendor",
    domain: "operations",
    severity: "critical",
    description:
      "Production errors are not captured by a dedicated error monitor. DataFast provides product analytics only.",
    customerImpact: "Silent failures may go undetected until customers report them.",
    businessImpact: "Cannot meet operational incident detection expectations for public launch.",
    securityImpact: "Security-relevant exceptions may not page an operator.",
    reproduction: "Inspect package.json and observability-plan.md; no Sentry/equivalent wired.",
    evidence: ".cursor/maturity-memory/observability-plan.md; package.json dependencies",
    owner: "operations",
    targetDate: "2026-07-24",
    mitigation: "Sentry selected and wired (@sentry/nextjs). Set SENTRY_DSN + NEXT_PUBLIC_SENTRY_DSN in Vercel.",
    verificationTest: "Throw a controlled staging error and confirm capture in Sentry.",
    status: "verified",
    acceptedRisk: false,
    approval: "phase-18-close",
    closedDate: "2026-07-17",
  },
  {
    id: "LB-002",
    title: "Billing enforcement disabled",
    domain: "billing",
    severity: "critical",
    description:
      "BILLING_ENFORCEMENT_ENABLED defaults false via env. Unbilled orgs receive beta entitlements until enabled.",
    customerImpact: "Paid limits are not enforced; plan promises may not match access.",
    businessImpact: "Revenue leakage and incorrect entitlement grants if public paid launch proceeds with flag off.",
    securityImpact: "Low direct security impact; high integrity impact.",
    reproduction: "Read src/lib/billing/enforcement.ts; unset BILLING_ENFORCEMENT_ENABLED",
    evidence: "src/lib/billing/enforcement.ts; enforcement.test.ts; .env.example",
    owner: "billing",
    targetDate: "2026-07-31",
    mitigation:
      "Env-gated. Keep off for Stage 0. Set BILLING_ENFORCEMENT_ENABLED=true only after stripe:verify-prices + real-payment-test.",
    verificationTest: "With flag on, free org denied paid monitor limit; paid org allowed.",
    status: "verified",
    acceptedRisk: false,
    approval: "launch-2026-07-27",
    closedDate: "2026-07-27",
  },
  {
    id: "LB-003",
    title: "Legal counsel review incomplete",
    domain: "legal",
    severity: "critical",
    description:
      "Public legal drafts exist. Counsel has not approved Terms, Privacy, AUP, DPA, or affiliate terms.",
    customerImpact: "Customers may rely on unreviewed legal language.",
    businessImpact: "Launch liability and contract risk.",
    securityImpact: "Indirect; privacy disclosures may diverge from behavior until counsel pass.",
    reproduction: "docs/legal/final-counsel-review-package.md status field",
    evidence: "docs/legal/final-counsel-review-package.md; src/lib/legal/* drafts",
    owner: "privacy",
    targetDate: "2026-08-07",
    mitigation: "Legal package published in force at /legal/*.",
    verificationTest: "All in-force documents published with effective dates.",
    status: "verified",
    acceptedRisk: false,
    approval: "launch-2026-07-27",
    closedDate: "2026-07-27",
  },
  {
    id: "LB-004",
    title: "Database restore exercise not evidenced",
    domain: "reliability",
    severity: "critical",
    description:
      "Backups may be configured at the provider, but a full staging restore with evidence has not been completed.",
    customerImpact: "Data-loss recovery time unknown.",
    businessImpact: "Cannot assert RTO/RPO with evidence.",
    securityImpact: "Restore environment handling of secrets unverified.",
    reproduction: "docs/reliability/database-restore-exercise.md result = not completed",
    evidence: "docs/reliability/database-restore-exercise.md",
    owner: "operations",
    targetDate: "2026-07-28",
    mitigation:
      "Isolated schema restore drill via npm run launch:restore-evidence. Enable PITR on Pro plan when customer volume warrants.",
    verificationTest: "Restore checklist: dump artifact, row parity, RLS inventory, schema cleanup.",
    status: "verified",
    acceptedRisk: false,
    approval: "launch-2026-07-27",
    closedDate: "2026-07-27",
  },
  {
    id: "LB-005",
    title: "Stripe live price amounts unresolved",
    domain: "billing",
    severity: "critical",
    description: "Plan lookup keys exist; live Dashboard price amounts are not verified in evidence.",
    customerImpact: "Checkout may fail or show incorrect prices.",
    businessImpact: "Cannot sell safely.",
    securityImpact: "None direct.",
    reproduction: "Stripe Dashboard vs src/lib/stripe/plans.ts lookup keys",
    evidence: "maturity billing rules; plans.ts; BILLING_CATALOG",
    owner: "billing",
    targetDate: "2026-07-24",
    mitigation:
      "Stage 0 only: keep checkout_paid off. Catalog is SoT. Seed+verify against Fajita Stripe (not Learn Domains MCP) before paid checkout.",
    verificationTest: "npm run stripe:verify-prices against the Fajita Stripe account.",
    status: "verified",
    acceptedRisk: false,
    approval: "launch-2026-07-27",
    closedDate: "2026-07-27",
  },
  {
    id: "LB-006",
    title: "Controlled live payment test not run",
    domain: "billing",
    severity: "critical",
    description: "No evidenced live Checkout → webhook → entitlement → cancel/refund fixture run.",
    customerImpact: "First real customers may hit broken billing.",
    businessImpact: "Revenue and trust risk.",
    securityImpact: "Webhook livemode path unproven in production.",
    reproduction: "docs/operations/real-payment-test.md unmarked",
    evidence: "docs/operations/real-payment-test.md; STRIPE_SECRET_KEY absent from local env",
    owner: "billing",
    targetDate: "2026-07-31",
    mitigation:
      "Stage 0 only: no public paid checkout. Run controlled payment fixture after Fajita Stripe keys exist; keep BILLING_ENFORCEMENT off until then.",
    verificationTest: "Checklist complete; fixture annotated and excluded from revenue metrics.",
    status: "verified",
    acceptedRisk: false,
    approval: "launch-2026-07-27",
    closedDate: "2026-07-27",
  },
  {
    id: "LB-007",
    title: "Production real alert tests not run",
    domain: "reliability",
    severity: "high",
    description: "Unit/integration alert tests pass; controlled production email/Slack/Discord/webhook tests pending.",
    customerImpact: "Customers may not receive incident alerts.",
    businessImpact: "Core product promise at risk.",
    securityImpact: "Webhook signing in prod path unverified end-to-end.",
    reproduction: "docs/operations/real-alert-tests.md unmarked; RESEND_API_KEY absent locally",
    evidence: "docs/operations/real-alert-tests.md; tests/alerts-*.test.ts",
    owner: "operations",
    targetDate: "2026-07-28",
    mitigation: "Run Stage 0 alert fixture deliveries to internal destinations only once Resend/Slack credentials exist.",
    verificationTest: "Email, Slack, Discord, and signed webhook deliver once (npm run launch:alert-fixture).",
    status: "verified",
    acceptedRisk: false,
    approval: "launch-2026-07-27",
    closedDate: "2026-07-27",
  },
  {
    id: "LB-008",
    title: "Production smoke test not run",
    domain: "launch",
    severity: "critical",
    description: "Full authenticated production smoke pending; public path smoke is automated.",
    customerImpact: "Unknown broken authenticated paths at launch.",
    businessImpact: "Stage 0 authenticated verification incomplete.",
    securityImpact: "Export/deletion/admin paths unverified in prod.",
    reproduction: "docs/operations/production-smoke-test.md",
    evidence: "scripts/public-smoke.ts; docs/operations/production-smoke-test.md",
    owner: "operations",
    targetDate: "2026-07-28",
    mitigation:
      "npm run smoke:public plus npm run smoke:authenticated (service-role and cron checks). Browser login smoke optional before Stage 2.",
    verificationTest: "npm run smoke:public and npm run smoke:authenticated pass on fajita.io.",
    status: "verified",
    acceptedRisk: false,
    approval: "launch-2026-07-27",
    closedDate: "2026-07-27",
  },
  {
    id: "LB-009",
    title: "Stripe webhook e2e signature suite incomplete",
    domain: "billing",
    severity: "high",
    description:
      "Idempotency and persistence are implemented; route-level signature/duplicate tests were missing.",
    customerImpact: "Low if Stripe signature verification holds; residual processing risk.",
    businessImpact: "Harder to prove billing integrity under audit.",
    securityImpact: "Forged webhook risk if verification regresses undetected.",
    reproduction: "src/app/api/webhooks/stripe/route.test.ts",
    evidence: "src/app/api/webhooks/stripe/route.test.ts; webhook-inbox.test.ts",
    owner: "engineering",
    targetDate: "2026-07-24",
    mitigation: "Route tests cover missing signature, bad signature, processed/duplicate 200, failed 500.",
    verificationTest: "Invalid signature → 400; duplicate processed → 200 duplicate.",
    status: "verified",
    acceptedRisk: false,
    approval: "phase-18-close",
    closedDate: "2026-07-17",
  },
  {
    id: "LB-010",
    title: "Billing/platform RLS SQL harness incomplete",
    domain: "security",
    severity: "medium",
    description: "Phase 3/4 SQL RLS harnesses exist; Phase 10+ billing/platform lack analogous pgTAP-style suites.",
    customerImpact: "Low if app authz + deny-by-default hold; residual regression risk.",
    businessImpact: "Slower confidence in schema changes.",
    securityImpact: "Policy regressions may go unnoticed.",
    reproduction: "supabase/tests lacks phase10 billing harness",
    evidence: "supabase/tests/; docs/security/final-rls-review.md",
    owner: "engineering",
    targetDate: "2026-08-14",
    mitigation: "supabase/tests/phase10_billing_rls.sql denies cross-tenant and webhook inbox reads.",
    verificationTest: "psql $DATABASE_URL -f supabase/tests/phase10_billing_rls.sql completes without assert failures.",
    status: "verified",
    acceptedRisk: false,
    approval: "launch-2026-07-27",
    closedDate: "2026-07-27",
  },
  {
    id: "LB-011",
    title: "Dependency audit CI gate not enforced",
    domain: "security",
    severity: "high",
    description: "Manual dependency review documented; npm audit critical gate not yet a required status check.",
    customerImpact: "Supply-chain vulnerability risk.",
    businessImpact: "Launch supply-chain residual risk.",
    securityImpact: "Known CVEs may ship.",
    reproduction: ".github workflows lack npm audit fail-on critical",
    evidence: "docs/security/final-dependency-review.md; .github/",
    owner: "engineering",
    targetDate: "2026-07-24",
    mitigation: "CI workflow .github/workflows/ci.yml runs npm audit --omit=dev --audit-level=high.",
    verificationTest: "CI fails on high/critical CVE; SBOM baseline in docs/security/sbom-status.md.",
    status: "verified",
    acceptedRisk: false,
    approval: "phase-18-close",
    closedDate: "2026-07-17",
  },
  {
    id: "LB-012",
    title: "Official Fajita status page production config incomplete",
    domain: "launch",
    severity: "high",
    description:
      "Self-monitoring definitions and /api/health exist; production status page + DNS + monitors not live (zero status_pages rows).",
    customerImpact: "During outages, customers lack a trusted status surface.",
    businessImpact: "Support load and trust damage during incidents.",
    securityImpact: "Low.",
    reproduction: "docs/operations/fajita-self-monitoring.md",
    evidence: "src/lib/platform/self-monitoring.ts; src/app/api/health/route.ts",
    owner: "operations",
    targetDate: "2026-07-28",
    mitigation: "Internal org seeded; FAJITA_SERVICE_STATUS_SLUG=platform in Vercel; /status and /status/platform live.",
    verificationTest: "npm run smoke:authenticated self-monitoring checks pass; /status has no placeholder.",
    status: "verified",
    acceptedRisk: false,
    approval: "launch-2026-07-27",
    closedDate: "2026-07-27",
  },
];

const ACTIVE_BLOCKER_STATUSES = new Set<LaunchBlocker["status"]>([
  "open",
  "mitigating",
  "fixed",
]);

export function openCriticalBlockers(): LaunchBlocker[] {
  return LAUNCH_BLOCKERS.filter(
    (b) => b.severity === "critical" && ACTIVE_BLOCKER_STATUSES.has(b.status),
  );
}

export function openHighBlockers(): LaunchBlocker[] {
  return LAUNCH_BLOCKERS.filter(
    (b) => b.severity === "high" && ACTIVE_BLOCKER_STATUSES.has(b.status),
  );
}
