import type { ReadinessGate } from "./types";

const TODAY = "2026-07-17";

/**
 * Final readiness scorecard gates. Statuses reflect inspected code, tests, and
 * ops evidence as of Phase 18. Do not mark passed without evidence paths.
 */
export const READINESS_GATES: ReadinessGate[] = [
  // Security
  {
    id: "SEC-AUTH",
    domain: "security",
    title: "Authentication flows (Clerk)",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "src/middleware.ts clerkMiddleware; src/lib/auth/*; docs/security/application-auth-and-tenancy.md; tests/app-invitations.test.ts",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: "docs/security/final-authentication-review.md",
    requiredApproval: "security",
    notes:
      "Clerk wired for /app and /internal. MFA and full production e2e auth matrix remain staging-verified, not production-smoked.",
  },
  {
    id: "SEC-SESSION",
    domain: "security",
    title: "Session security (provider cookies)",
    severity: "critical",
    status: "passed_with_condition",
    evidence: "Clerk session cookies; no custom session crypto; docs/security/final-authentication-review.md",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: "security",
  },
  {
    id: "SEC-TENANT",
    domain: "security",
    title: "Tenant isolation (cross-org)",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "supabase/tests/phase3_rls_isolation.sql; phase4_monitoring_rls.sql; org-scoped server loaders; docs/security/final-rls-review.md",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: "LB-010",
    relatedRunbook: "docs/security/final-authorization-review.md",
    requiredApproval: "security",
    notes: "SQL harnesses exist for Phase 3/4. Billing/platform RLS rely on deny-by-default; full adversarial suite not re-run in prod.",
  },
  {
    id: "SEC-RLS",
    domain: "security",
    title: "Row-level security inventory",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "scripts/rls-inventory.ts; companion *_rls.sql migrations; docs/security/final-rls-review.md",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: "security",
  },
  {
    id: "SEC-SSRF",
    domain: "security",
    title: "SSRF / DNS rebinding / redirect safety",
    severity: "critical",
    status: "passed",
    evidence:
      "services/monitor-worker/internal/destination/*_test.go (pass 2026-07-17); executor_test.go; src/lib/monitoring/destination.ts; tests/alerts-ssrf.test.ts; docs/security/monitoring-ssrf-defense.md",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: "docs/security/final-ssrf-review.md",
    requiredApproval: "security",
  },
  {
    id: "SEC-SECRETS",
    domain: "security",
    title: "Secret storage and scanning",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "scripts/secret-scan.ts; docs/security/final-secret-management-review.md; .env* gitignored; content/docs validators",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: "security",
    notes: "Repo scan passes for committed tree. Production rotation exercises remain staged/planned.",
  },
  {
    id: "SEC-ADMIN",
    domain: "security",
    title: "Platform admin /internal hardening",
    severity: "critical",
    status: "passed",
    evidence:
      "src/app/internal/layout.tsx allowInternalPage; robots noindex; src/lib/platform/access.ts; tests/brand-lab-protection.test.tsx",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: "docs/security/final-admin-security-review.md",
    requiredApproval: "security",
  },
  {
    id: "SEC-WEBHOOKS",
    domain: "security",
    title: "Inbound webhook signatures and idempotency",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "src/lib/billing/webhook-processor.ts; billing_webhook_events; src/lib/billing/webhook-inbox.ts; tests; docs/security/final-webhook-review.md",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: "LB-009",
    relatedRunbook: null,
    requiredApproval: "billing",
    notes: "Idempotency implemented. Full Stripe signature e2e against live endpoint not yet production-smoked.",
  },
  {
    id: "SEC-DEPS",
    domain: "security",
    title: "Dependency and supply-chain review",
    severity: "high",
    status: "passed_with_condition",
    evidence:
      ".github/workflows/ci.yml audit-level=high; docs/security/sbom-status.md; moderate postcss via next remains",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: "LB-011",
    relatedRunbook: null,
    requiredApproval: "security",
  },
  {
    id: "SEC-APM",
    domain: "security",
    title: "Error monitoring / APM wired",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "@sentry/nextjs; sentry.server.config.ts; src/instrumentation.ts; global-error.tsx; isSentryConfigured(); DSN required in Vercel",
    owner: "operations",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: "LB-001",
    relatedRunbook: "docs/operations/final-incident-response-plan.md",
    requiredApproval: "operations",
    notes: "SDK disabled until SENTRY_DSN is set. Create Fajita Sentry project and set env before Stage 1.",
  },

  // Billing
  {
    id: "BILL-WEBHOOK",
    domain: "billing",
    title: "Stripe webhook persistence and reconciliation",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "src/lib/billing/webhook-processor.ts syncSubscription + writeEntitlementSnapshot; billing_subscriptions upsert",
    owner: "billing",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: "docs/readiness/final-production-readiness.md",
    requiredApproval: "billing",
  },
  {
    id: "BILL-ENFORCE",
    domain: "billing",
    title: "Entitlement enforcement enabled for paid launch",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "src/lib/billing/enforcement.ts env-gated; defaults off; Stage-0 accepted risk LB-002",
    owner: "billing",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: true,
    relatedIssue: "LB-002",
    relatedRunbook: "docs/operations/staged-launch-plan.md",
    requiredApproval: "billing",
    notes: "Must set BILLING_ENFORCEMENT_ENABLED=true before Stage 2 public paid launch.",
  },
  {
    id: "BILL-PRICES",
    domain: "billing",
    title: "Live Stripe prices verified",
    severity: "critical",
    status: "accepted_risk",
    evidence:
      "Stage 0 accepted risk: checkout_paid stays off until npm run stripe:verify-prices on Fajita Stripe. Do not seed Learn Domains.",
    owner: "billing",
    lastTested: TODAY,
    expiration: "2026-08-31",
    blocking: true,
    relatedIssue: "LB-005",
    relatedRunbook: "scripts/stripe-seed-products.ts",
    requiredApproval: "billing",
    notes: "Must reach passed before Stage 2.",
  },
  {
    id: "BILL-LIVE-PAY",
    domain: "billing",
    title: "Controlled live payment test",
    severity: "critical",
    status: "accepted_risk",
    evidence:
      "Stage 0 accepted risk: no public paid checkout until docs/operations/real-payment-test.md passes.",
    owner: "billing",
    lastTested: TODAY,
    expiration: "2026-08-31",
    blocking: true,
    relatedIssue: "LB-006",
    relatedRunbook: "docs/operations/real-payment-test.md",
    requiredApproval: "billing",
    notes: "Must reach passed before Stage 2.",
  },

  // Reliability
  {
    id: "REL-SCHEDULER",
    domain: "reliability",
    title: "Scheduler lease / SKIP LOCKED reliability",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "services/monitor-worker; supabase/tests/phase4_scheduler.sql; docs/reliability/final-monitoring-review.md",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: "operations",
  },
  {
    id: "REL-INCIDENT",
    domain: "reliability",
    title: "Incident state machine",
    severity: "critical",
    status: "passed",
    evidence: "tests/incidents-state-machine.test.ts; docs/reliability/final-incident-review.md",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: null,
  },
  {
    id: "REL-ALERTS",
    domain: "reliability",
    title: "Alert delivery reliability",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "tests/alerts-*.test.ts; alert-worker; docs/reliability/final-alert-review.md; production real-alert tests pending",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: true,
    relatedIssue: "LB-007",
    relatedRunbook: "docs/operations/real-alert-tests.md",
    requiredApproval: "operations",
  },
  {
    id: "REL-STATUS",
    domain: "reliability",
    title: "Status-page independence",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "src/app/(status)/layout.tsx; middleware statusHostRewrite before auth protect; docs/reliability/final-status-page-review.md",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: null,
  },
  {
    id: "REL-RESTORE",
    domain: "reliability",
    title: "Database restore exercise",
    severity: "critical",
    status: "accepted_risk",
    evidence:
      "Stage 0 accepted risk: no customer volume. Isolated restore required before Stage 1 (docs/reliability/database-restore-exercise.md).",
    owner: "operations",
    lastTested: TODAY,
    expiration: "2026-08-31",
    blocking: true,
    relatedIssue: "LB-004",
    relatedRunbook: "docs/reliability/disaster-recovery-plan.md",
    requiredApproval: "operations",
    notes: "Must reach passed before Stage 1.",
  },
  {
    id: "REL-LOAD",
    domain: "reliability",
    title: "Load / stress / soak / chaos evidence",
    severity: "high",
    status: "passed_with_condition",
    evidence:
      "docs/testing/phase-17-load-results.md and prior phase matrices; Phase 18 chaos/soak staging packages documented with limits",
    owner: "operations",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: "docs/reliability/load-test-results.md",
    requiredApproval: null,
    notes: "Prior phase load results reused. Full 10x launch stress and multi-day soak not re-executed in Phase 18 window.",
  },

  // Privacy / legal
  {
    id: "PRIV-MAP",
    domain: "privacy",
    title: "Privacy data map complete",
    severity: "critical",
    status: "passed_with_condition",
    evidence: "docs/privacy/final-data-map.md; phase-17-data-map.md; maturity data-inventory.md",
    owner: "privacy",
    lastTested: TODAY,
    expiration: "2026-09-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: "privacy",
  },
  {
    id: "PRIV-EXPORT",
    domain: "privacy",
    title: "Data export / deletion paths",
    severity: "critical",
    status: "passed_with_condition",
    evidence: "docs/privacy/final-export-review.md; final-deletion-review.md; platform privacy queues",
    owner: "privacy",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: "privacy",
    notes: "Provider deletion propagation remains documented as pending-complete, not silently claimed finished.",
  },
  {
    id: "LEGAL-COUNSEL",
    domain: "legal",
    title: "Counsel review of legal package",
    severity: "critical",
    status: "accepted_risk",
    evidence:
      "Stage 0 accepted risk: legal drafts stay Draft / Counsel review required. No counsel-approved public claim.",
    owner: "privacy",
    lastTested: TODAY,
    expiration: "2026-08-31",
    blocking: true,
    relatedIssue: "LB-003",
    relatedRunbook: null,
    requiredApproval: "privacy",
    notes: "Must reach passed before Stage 2 / public paid signup.",
  },
  {
    id: "LEGAL-CLAIMS",
    domain: "legal",
    title: "Public claims accuracy",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "src/lib/site/claims.ts; /internal/product/claims; docs/product/public-claims-registry.md; no SOC2/HIPAA claims in copy scan",
    owner: "product",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: "product",
  },

  // Performance / a11y
  {
    id: "PERF-PUBLIC",
    domain: "performance",
    title: "Public Core Web Vitals budgets",
    severity: "high",
    status: "passed_with_condition",
    evidence: "docs/performance/final-performance-audit.md; prior phase budgets; Lighthouse re-measure pending Stage 0",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-01",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: null,
  },
  {
    id: "A11Y-FINAL",
    domain: "accessibility",
    title: "Final accessibility audit",
    severity: "high",
    status: "passed_with_condition",
    evidence: "docs/accessibility/final-accessibility-audit.md; keyboard/focus patterns in app shell",
    owner: "engineering",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: null,
  },

  // Operations / launch
  {
    id: "OPS-DR",
    domain: "operations",
    title: "Disaster recovery plan and tabletops",
    severity: "critical",
    status: "passed_with_condition",
    evidence:
      "docs/reliability/disaster-recovery-plan.md; docs/operations/tabletop-exercises.md (tabletop recorded; restore exercise open)",
    owner: "operations",
    lastTested: TODAY,
    expiration: "2026-08-17",
    blocking: true,
    relatedIssue: "LB-004",
    relatedRunbook: "docs/reliability/disaster-recovery-plan.md",
    requiredApproval: "operations",
  },
  {
    id: "OPS-SMOKE",
    domain: "launch",
    title: "Production smoke test",
    severity: "critical",
    status: "accepted_risk",
    evidence:
      "Stage 0 accepted risk: public smoke via scripts/public-smoke.ts; authenticated smoke before Stage 1.",
    owner: "operations",
    lastTested: TODAY,
    expiration: "2026-08-31",
    blocking: true,
    relatedIssue: "LB-008",
    relatedRunbook: "docs/operations/production-smoke-test.md",
    requiredApproval: "operations",
    notes: "Must reach passed before Stage 1.",
  },
  {
    id: "OPS-LAUNCH-CC",
    domain: "launch",
    title: "Launch-day command center",
    severity: "high",
    status: "passed",
    evidence: "/internal/launch; src/lib/platform/readiness/launch.ts; docs/operations/launch-day-command-center.md",
    owner: "operations",
    lastTested: TODAY,
    expiration: "2026-09-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: null,
  },
  {
    id: "OPS-SELF-MON",
    domain: "launch",
    title: "Fajita self-monitoring and status page",
    severity: "high",
    status: "in_progress",
    evidence: "docs/operations/staged-launch-plan.md Stage 0 checklist; official status page fixtures pending production config",
    owner: "operations",
    lastTested: TODAY,
    expiration: "2026-08-01",
    blocking: true,
    relatedIssue: "LB-012",
    relatedRunbook: null,
    requiredApproval: "operations",
  },
  {
    id: "XFER-PACKAGE",
    domain: "transfer",
    title: "Acquisition transfer package",
    severity: "high",
    status: "passed",
    evidence: "docs/handoff/acquisition-transfer-package.md; production-ownership-manifest.md; transfer-dry-run.md",
    owner: "operations",
    lastTested: TODAY,
    expiration: "2026-10-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: null,
    requiredApproval: null,
  },
  {
    id: "XFER-KEYPERSON",
    domain: "transfer",
    title: "Key-person risk documentation",
    severity: "high",
    status: "passed_with_condition",
    evidence: "docs/operations/key-person-risk.md; backup owner placeholders require named successors",
    owner: "operations",
    lastTested: TODAY,
    expiration: "2026-09-17",
    blocking: false,
    relatedIssue: null,
    relatedRunbook: "docs/operations/business-continuity.md",
    requiredApproval: null,
  },
];

export function gatesByDomain(domain: ReadinessGate["domain"]): ReadinessGate[] {
  return READINESS_GATES.filter((g) => g.domain === domain);
}

export function blockingFailedGates(): ReadinessGate[] {
  return READINESS_GATES.filter(
    (g) =>
      g.blocking &&
      (g.status === "failed" ||
        g.status === "not_started" ||
        g.status === "blocked" ||
        g.status === "in_progress"),
  );
}
