import type { AcceptedRisk, KnownLimitation } from "./types";

export const KNOWN_LIMITATIONS: KnownLimitation[] = [
  {
    id: "LIM-001",
    limitation: "No SMS or phone alerts",
    productArea: "alerts",
    impact: "Teams that require SMS paging must use email/Slack/Discord/webhook bridges.",
    workaround: "Route webhooks to an external paging tool.",
    customerFacingDisclosure: "Alert channels are email, Slack, Discord, and HTTPS webhooks.",
    owner: "product",
    priority: "p2",
    plannedReview: "2026-10-01",
    acceptedRisk: true,
    publicSafe: true,
  },
  {
    id: "LIM-002",
    limitation: "No private-network or agent-based monitoring",
    productArea: "monitoring",
    impact: "Internal services behind NAT cannot be checked directly.",
    workaround: "Expose a public health endpoint or use heartbeats.",
    customerFacingDisclosure: "Fajita monitors publicly reachable HTTP(S) endpoints, certificates, and heartbeats.",
    owner: "product",
    priority: "p2",
    plannedReview: "2026-10-01",
    acceptedRisk: true,
    publicSafe: true,
  },
  {
    id: "LIM-003",
    limitation: "No browser / RUM / mobile apps",
    productArea: "monitoring",
    impact: "Client-side failures are out of scope.",
    workaround: "Monitor critical API and page endpoints from the server side.",
    customerFacingDisclosure: "Fajita is server-side uptime monitoring, not real-user monitoring.",
    owner: "product",
    priority: "p3",
    plannedReview: "2026-12-01",
    acceptedRisk: true,
    publicSafe: true,
  },
  {
    id: "LIM-004",
    limitation: "No public API or SDKs",
    productArea: "platform",
    impact: "Programmatic account management is unavailable.",
    workaround: "Use the web application.",
    customerFacingDisclosure: "Management is through the Fajita web app.",
    owner: "product",
    priority: "p2",
    plannedReview: "2026-12-01",
    acceptedRisk: true,
    publicSafe: true,
  },
  {
    id: "LIM-005",
    limitation: "No SAML / SCIM / enterprise contract tooling",
    productArea: "auth",
    impact: "Enterprise IdP provisioning is unavailable.",
    workaround: "Use Clerk-supported sign-in methods and org invites.",
    customerFacingDisclosure: "Team access uses organization invitations.",
    owner: "product",
    priority: "p3",
    plannedReview: "2027-01-01",
    acceptedRisk: true,
    publicSafe: true,
  },
  {
    id: "LIM-006",
    limitation: "No guaranteed uptime or alert delivery SLA",
    productArea: "legal",
    impact: "Customers cannot rely on contractual uptime guarantees.",
    workaround: "Status page + best-effort multi-channel alerts.",
    customerFacingDisclosure:
      "Service is provided as available. Monitoring and alerts can fail; see Terms and status page.",
    owner: "legal",
    priority: "p1",
    plannedReview: "2026-09-01",
    acceptedRisk: true,
    publicSafe: true,
  },
  {
    id: "LIM-007",
    limitation: "Networked free HTTP status checker deferred",
    productArea: "tools",
    impact: "Public free tool does not fetch arbitrary URLs.",
    workaround: "Use paid monitors after signup.",
    customerFacingDisclosure: "Some free tools are calculators only; networked checks require an account.",
    owner: "security",
    priority: "p1",
    plannedReview: "2026-09-01",
    acceptedRisk: true,
    publicSafe: true,
  },
  {
    id: "LIM-008",
    limitation: "No 24/7 staffed support",
    productArea: "support",
    impact: "Human response is best-effort during founder coverage windows.",
    workaround: "Pamphlet chatbot + email handoff; status page during incidents.",
    customerFacingDisclosure: "Support is not live chat staffing. Response times are not guaranteed.",
    owner: "operations",
    priority: "p1",
    plannedReview: "2026-09-01",
    acceptedRisk: true,
    publicSafe: true,
  },
];

export const ACCEPTED_RISKS: AcceptedRisk[] = [
  {
    id: "AR-001",
    risk: "No independent penetration test before initial launch",
    severity: "high",
    evidence: "docs/security/vulnerability-management.md external review package prepared",
    whyNotFixed: "Commercial timeline; internal adversarial tests and SSRF/RLS suites exist.",
    mitigation: "External review package ready; responsible disclosure policy published; Stage 0 limited audience.",
    monitoring: "Security queue in /internal/security; disclosure inbox",
    owner: "security",
    expiration: "2026-10-01",
    reviewDate: "2026-08-15",
    approver: "founder Stage-0 (Conditionally Ready; expires with Stage-2 gate)",
  },
  {
    id: "AR-002",
    risk: "Solo-founder multi-role incident command",
    severity: "medium",
    evidence: "docs/operations/key-person-risk.md",
    whyNotFixed: "Headcount constraint at launch.",
    mitigation: "Documented roles, runbooks, provider support contacts, backup access procedures.",
    monitoring: "Launch command center; calendar coverage",
    owner: "operations",
    expiration: "2026-12-01",
    reviewDate: "2026-09-01",
    approver: "founder Stage-0 (Conditionally Ready; expires with Stage-2 gate)",
  },
  {
    id: "AR-003",
    risk: "Phase 18 did not re-run multi-day soak at 10x capacity",
    severity: "medium",
    evidence: "docs/reliability/soak-test-results.md; prior phase load results",
    whyNotFixed: "Timeboxed Phase 18; prior load evidence reused with documented limits.",
    mitigation: "Capacity model + stop conditions; Stage 1 monitor caps.",
    monitoring: "Queue lag metrics; launch stop conditions",
    owner: "operations",
    expiration: "2026-08-31",
    reviewDate: "2026-08-07",
    approver: "founder Stage-0 (Conditionally Ready; expires with Stage-2 gate)",
  },
];
