import { computeCac, computePayback, estimateMonthlyContributionCents } from "./metrics";
import type { ChannelRecord, ChannelScorecard, ChannelState } from "./types";

export const DEFAULT_CHANNEL_STOP_CONDITIONS = [
  "Activation below approved threshold",
  "Retention below approved threshold",
  "Refund rate above threshold",
  "Chargeback rate above threshold",
  "Support burden above threshold",
  "Cost above approved budget",
  "Retained CAC above approved ceiling",
  "Payback above approved ceiling",
  "Security abuse increase",
  "Affiliate fraud increase",
  "Monitoring capacity stress",
  "Alert-delivery degradation",
  "Misleading partner claims",
  "Legal or trademark issue",
  "Customer-quality mismatch",
  "Data insufficient after maximum test period",
];

/** Seed inventory. States reflect pre-scale reality under Stage 0. */
export const CHANNEL_INVENTORY: ChannelRecord[] = [
  {
    key: "organic_search",
    name: "Organic search",
    type: "organic_search",
    state: "holding",
    decisionReason: "Maintain existing organic; do not accelerate until gate clears",
    owner: "founder",
    budgetCapCents: 0,
    volumeCap: null,
    reviewDate: "2026-08-01",
    primaryMetric: "activated_paid_organizations",
    guardrails: ["No programmatic SEO spam", "No thin page expansion"],
    stopConditions: DEFAULT_CHANNEL_STOP_CONDITIONS,
  },
  {
    key: "documentation",
    name: "Documentation",
    type: "documentation",
    state: "holding",
    decisionReason: "Support and activation asset; not a growth accelerator yet",
    owner: "founder",
    budgetCapCents: 0,
    volumeCap: null,
    reviewDate: "2026-08-01",
    primaryMetric: "activated_paid_organizations",
    guardrails: ["Docs accuracy over volume"],
    stopConditions: DEFAULT_CHANNEL_STOP_CONDITIONS,
  },
  {
    key: "blog",
    name: "Blog",
    type: "blog",
    state: "researching",
    decisionReason: "Await Phase 19 growth-quality baselines before compounding investment",
    owner: "founder",
    budgetCapCents: 0,
    volumeCap: null,
    reviewDate: "2026-08-15",
    primaryMetric: "retained_new_mrr",
    guardrails: ["Tiered investment only", "No publication volume targets"],
    stopConditions: DEFAULT_CHANNEL_STOP_CONDITIONS,
  },
  {
    key: "affiliates",
    name: "Affiliates",
    type: "affiliate",
    state: "holding",
    decisionReason: "Phase 12 ledger remains authoritative; no scale recruitment until gate clears",
    owner: "affiliate_operations",
    budgetCapCents: null,
    volumeCap: null,
    reviewDate: "2026-08-01",
    primaryMetric: "day7_retained_organizations",
    guardrails: [
      "No silent commission changes",
      "Quality includes activation and retention",
      "No mass outreach",
    ],
    stopConditions: DEFAULT_CHANNEL_STOP_CONDITIONS,
  },
  {
    key: "customer_referrals",
    name: "Customer referrals",
    type: "customer_referral",
    state: "preparing",
    decisionReason: "Foundation shipping in Phase 20; prompts gated on eligibility",
    owner: "founder",
    budgetCapCents: 0,
    volumeCap: null,
    reviewDate: "2026-08-15",
    primaryMetric: "day7_retained_organizations",
    guardrails: ["No cash rewards without ledger approval", "Distinct from affiliate attribution"],
    stopConditions: DEFAULT_CHANNEL_STOP_CONDITIONS,
  },
  {
    key: "paid_search",
    name: "Paid search",
    type: "paid_search",
    state: "paused",
    decisionReason: "Paid acquisition gate closed while scale readiness is Not eligible",
    owner: "founder",
    budgetCapCents: 0,
    volumeCap: 0,
    reviewDate: "2026-09-01",
    primaryMetric: "day7_retained_cac",
    guardrails: [
      "High-intent exact/phrase only initially",
      "No competitor trademark misuse",
      "Hard daily and total caps",
    ],
    stopConditions: DEFAULT_CHANNEL_STOP_CONDITIONS,
  },
  {
    key: "paid_social",
    name: "Paid social",
    type: "paid_social",
    state: "rejected",
    decisionReason: "No evidence of retained fit; rejected for Stage 0",
    owner: "founder",
    budgetCapCents: 0,
    volumeCap: 0,
    reviewDate: "2026-10-01",
    primaryMetric: "day7_retained_organizations",
    guardrails: ["No fear manipulation", "No fake outage creative"],
    stopConditions: DEFAULT_CHANNEL_STOP_CONDITIONS,
  },
  {
    key: "partnerships",
    name: "Partnerships",
    type: "partnership",
    state: "researching",
    decisionReason: "Registry ready; no launches until gate and diligence clear",
    owner: "founder",
    budgetCapCents: 0,
    volumeCap: null,
    reviewDate: "2026-08-15",
    primaryMetric: "retained_new_mrr",
    guardrails: ["No logo-only partnerships", "No customer data sharing"],
    stopConditions: DEFAULT_CHANNEL_STOP_CONDITIONS,
  },
  {
    key: "unknown",
    name: "Unknown attribution",
    type: "unknown",
    state: "holding",
    decisionReason: "Unknown must remain unknown; never overwrite with direct",
    owner: "founder",
    budgetCapCents: null,
    volumeCap: null,
    reviewDate: "2026-08-01",
    primaryMetric: "attribution_completeness",
    guardrails: ["No invented attribution"],
    stopConditions: DEFAULT_CHANNEL_STOP_CONDITIONS,
  },
];

export function channelsByState(state: ChannelState): ChannelRecord[] {
  return CHANNEL_INVENTORY.filter((c) => c.state === state);
}

export function pauseChannel(
  channel: ChannelRecord,
  reason: string,
): ChannelRecord {
  return {
    ...channel,
    state: "paused",
    decisionReason: reason,
  };
}

/** Fixture scorecards for lab and empty-state education. Not production truth. */
export function buildFixtureScorecards(): ChannelScorecard[] {
  const organic = CHANNEL_INVENTORY.find((c) => c.key === "organic_search")!;
  const affiliate = CHANNEL_INVENTORY.find((c) => c.key === "affiliates")!;
  const paidSocial = CHANNEL_INVENTORY.find((c) => c.key === "paid_social")!;

  const organicCac = computeCac({
    eligibleChannelCostCents: 120_000,
    activatedPaidOrganizations: 8,
    day7RetainedOrganizations: 6,
    day30RetainedOrganizations: null,
    fullyLoadedCostCents: 180_000,
    cohortDate: "2026-06-01",
    channel: organic.key,
    completeness: "partial",
    costAllocationMethod: "content_allocation + tooling",
  });

  const contribution = estimateMonthlyContributionCents({
    collectedSubscriptionCents: 4900,
    paymentFeesCents: 200,
    monitoringComputeCents: 400,
    databaseCents: 150,
    alertDeliveryCents: 80,
    subscriberEmailCents: 40,
    supportCents: 300,
    affiliateCommissionCents: 0,
  });

  const organicPayback = computePayback({
    cacCents: organicCac.day7RetainedCacCents,
    expectedMonthlyContributionCents: contribution,
    cohortDate: "2026-06-01",
    completeness: "partial",
    includedCosts: [
      "payment fees",
      "monitoring compute",
      "database",
      "alerts",
      "subscriber email",
      "support",
    ],
    excludedCosts: ["general overhead", "founder salary"],
    assumptions: ["Contribution constant for first 6 months", "No expansion assumed"],
  });

  const affiliateCac = computeCac({
    eligibleChannelCostCents: 98_000,
    activatedPaidOrganizations: 10,
    day7RetainedOrganizations: 9,
    day30RetainedOrganizations: 7,
    fullyLoadedCostCents: 98_000,
    cohortDate: "2026-05-01",
    channel: affiliate.key,
    completeness: "complete",
    costAllocationMethod: "affiliate_commission_ledger",
  });

  const poorCac = computeCac({
    eligibleChannelCostCents: 250_000,
    activatedPaidOrganizations: 4,
    day7RetainedOrganizations: 1,
    day30RetainedOrganizations: 0,
    fullyLoadedCostCents: 280_000,
    cohortDate: "2026-04-01",
    channel: paidSocial.key,
    completeness: "complete",
    costAllocationMethod: "ad_provider_import",
  });

  return [
    {
      channel: organic,
      visitors: 4200,
      qualifiedVisitors: 980,
      signups: 42,
      paidOrganizations: 10,
      activatedOrganizations: 8,
      day7Retained: 6,
      day30Retained: null,
      mrrCents: 49_000,
      retainedMrrCents: 29_400,
      refundsCents: 0,
      chargebacks: 0,
      supportContacts: 3,
      securityAbuseEvents: 0,
      costCents: 120_000,
      activatedCacCents: organicCac.directActivatedCacCents,
      retainedCacCents: organicCac.day7RetainedCacCents,
      paybackMonths: organicPayback.paybackMonths,
      contributionCents: contribution * 6,
      confidence: "medium",
      completeness: "partial",
      meta: organicCac.meta,
    },
    {
      channel: affiliate,
      visitors: 1100,
      qualifiedVisitors: 640,
      signups: 28,
      paidOrganizations: 12,
      activatedOrganizations: 10,
      day7Retained: 9,
      day30Retained: 7,
      mrrCents: 58_800,
      retainedMrrCents: 44_100,
      refundsCents: 4_900,
      chargebacks: 0,
      supportContacts: 4,
      securityAbuseEvents: 0,
      costCents: 98_000,
      activatedCacCents: affiliateCac.directActivatedCacCents,
      retainedCacCents: affiliateCac.day7RetainedCacCents,
      paybackMonths: computePayback({
        cacCents: affiliateCac.day7RetainedCacCents,
        expectedMonthlyContributionCents: contribution - 900,
        cohortDate: "2026-05-01",
        completeness: "complete",
        includedCosts: ["affiliate commission", "payment fees", "compute", "support"],
        excludedCosts: ["general overhead"],
        assumptions: ["Commission continues per Phase 12 terms"],
      }).paybackMonths,
      contributionCents: (contribution - 900) * 7,
      confidence: "high",
      completeness: "complete",
      meta: affiliateCac.meta,
    },
    {
      channel: paidSocial,
      visitors: 18000,
      qualifiedVisitors: 400,
      signups: 90,
      paidOrganizations: 6,
      activatedOrganizations: 4,
      day7Retained: 1,
      day30Retained: 0,
      mrrCents: 11_400,
      retainedMrrCents: 0,
      refundsCents: 9_800,
      chargebacks: 1,
      supportContacts: 22,
      securityAbuseEvents: 2,
      costCents: 250_000,
      activatedCacCents: poorCac.directActivatedCacCents,
      retainedCacCents: poorCac.day7RetainedCacCents,
      paybackMonths: null,
      contributionCents: -40_000,
      confidence: "high",
      completeness: "complete",
      meta: poorCac.meta,
    },
  ];
}
