/** Shared publication review flags for the Phase 15 launch set. */
export const LAUNCH_REVIEWS = {
  status: "published" as const,
  author: "fajita-editorial",
  owner: "content-editorial",
  reviewers: ["product", "engineering", "editorial"],
  publishedAt: "2026-07-17",
  updatedAt: "2026-07-17",
  lastReviewedAt: "2026-07-17",
  nextReviewDue: "2027-01-17",
  contentVersion: "1",
  productVersion: "1.0",
  technicalReviewPassed: true,
  editorialReviewPassed: true,
  productReviewPassed: true,
  securityReviewPassed: true,
  originalityReviewPassed: true,
  antiAiSlopPassed: true,
  indexable: true,
  canonical: true,
  llmInclude: true,
  requiresProductReview: true,
  requiresSecurityReview: false,
  requiresLegalReview: false,
};
