/**
 * Builds the Ask Fajita knowledge bundle from approved product sources.
 * Run: npm run chat:knowledge
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  INDUSTRY_CONTEXT,
  OBJECTION_PLAYBOOK,
  SALES_CLOSES,
} from "../src/lib/ai/fajita-chat/industry-playbook";
import { listKnowledgeSources } from "../src/lib/support/knowledge/registry";

const OUT = resolve(
  process.cwd(),
  "src/lib/ai/fajita-chat/knowledge-bundle.generated.ts",
);

function escapeForTemplate(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main() {
  const sources = listKnowledgeSources();
  const corpus = sources
    .sort((a, b) => b.authorityLevel - a.authorityLevel)
    .map((s) => {
      const body = s.body.slice(0, 12_000);
      return `### ${s.title} (${s.sourceId})\nURL: ${s.canonicalUrl}\nAuthority: ${s.authorityLevel}\n${body}`;
    })
    .join("\n\n---\n\n");

  const bundle = [
    "# Fajita product knowledge (approved sources only)",
    "",
    INDUSTRY_CONTEXT,
    "",
    OBJECTION_PLAYBOOK,
    "",
    SALES_CLOSES,
    "",
    "## Registered product sources",
    "",
    corpus,
  ].join("\n");

  const generated = `/**
 * AUTO-GENERATED by scripts/build-fajita-chat-knowledge.ts
 * Do not edit by hand. Run: npm run chat:knowledge
 */
export const FAJITA_CHAT_KNOWLEDGE_BUNDLE = \`${escapeForTemplate(bundle)}\`;

export const FAJITA_CHAT_KNOWLEDGE_META = {
  sourceCount: ${sources.length},
  generatedAt: "${new Date().toISOString().slice(0, 10)}",
  version: "2026.07",
} as const;
`;

  writeFileSync(OUT, generated, "utf8");
  console.log(
    `Wrote knowledge bundle (${sources.length} sources, ${bundle.length} chars) → ${OUT}`,
  );
}

main();
