/**
 * One-time wordmark generation. Typesets "Fajita" in Fraunces (OFL) at the
 * brand display instance, replaces the "j" tittle with a separate ember dot,
 * and writes SVG path data consumed by the wordmark component.
 *
 * Run: npx tsx scripts/generate-wordmark.ts
 * Requires: .brand-src/Fraunces-var.ttf (gitignored source asset)
 */
import * as fontkit from "fontkit";
import { writeFileSync } from "node:fs";
import path from "node:path";

const fontPath = path.join(process.cwd(), ".brand-src", "Fraunces-var.ttf");
const loaded = fontkit.openSync(fontPath);
const base = ("fonts" in loaded ? (loaded as fontkit.FontCollection).fonts[0] : loaded) as fontkit.Font;

// Brand display instance: weight 560, display optical size, no softness/wonk.
const font = base.getVariation({ wght: 600, opsz: 144, SOFT: 0, WONK: 0 });

// Dotless j (U+0237) so the tittle can become the ember dot.
const text = "Fa\u0237ita";
const run = font.layout(text);

const upem = font.unitsPerEm;
const scale = 100 / upem; // normalize to a 100-unit cap-ish height space
const ascent = font.ascent * scale;
const descent = font.descent * scale; // negative

let x = 0;
const pieces: string[] = [];
for (let i = 0; i < run.glyphs.length; i++) {
  const glyph = run.glyphs[i];
  const pos = run.positions[i];
  const fn = glyph.path.toFunction();
  const ctx = new PathCollector((x + pos.xOffset) * scale, scale);
  fn(ctx as unknown as CanvasRenderingContext2D);
  pieces.push(ctx.toString());
  x += pos.xAdvance;
}

const width = x * scale;

// Collector that converts fontkit path commands to a translated,
// y-flipped SVG path string.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function PathCollector(this: any, dx: number, s: number) {
  const parts: string[] = [];
  const fx = (v: number) => +(v * s + dx).toFixed(2);
  const fy = (v: number) => +(ascent - v * s).toFixed(2);
  this.moveTo = (px: number, py: number) => parts.push(`M${fx(px)} ${fy(py)}`);
  this.lineTo = (px: number, py: number) => parts.push(`L${fx(px)} ${fy(py)}`);
  this.quadraticCurveTo = (cx: number, cy: number, px: number, py: number) =>
    parts.push(`Q${fx(cx)} ${fy(cy)} ${fx(px)} ${fy(py)}`);
  this.bezierCurveTo = (
    c1x: number,
    c1y: number,
    c2x: number,
    c2y: number,
    px: number,
    py: number,
  ) =>
    parts.push(
      `C${fx(c1x)} ${fy(c1y)} ${fx(c2x)} ${fy(c2y)} ${fx(px)} ${fy(py)}`,
    );
  this.closePath = () => parts.push("Z");
  this.toString = () => parts.join("");
}

const height = ascent - descent;

// Locate the true tittle of the regular "j" glyph: the contour that sits
// entirely above the x-height. The ember dot takes its exact place.
const jIndex = 2;
let jx = 0;
for (let i = 0; i < jIndex; i++) jx += run.positions[i].xAdvance;

const jRun = font.layout("j");
const jGlyph = jRun.glyphs[0];
const xHeight = font.xHeight;
type Pt = { x: number; y: number };
const contours: Pt[][] = [];
let current: Pt[] = [];
const collector = {
  moveTo(px: number, py: number) {
    if (current.length) contours.push(current);
    current = [{ x: px, y: py }];
  },
  lineTo(px: number, py: number) {
    current.push({ x: px, y: py });
  },
  quadraticCurveTo(cx: number, cy: number, px: number, py: number) {
    current.push({ x: cx, y: cy }, { x: px, y: py });
  },
  bezierCurveTo(
    c1x: number,
    c1y: number,
    c2x: number,
    c2y: number,
    px: number,
    py: number,
  ) {
    current.push({ x: c1x, y: c1y }, { x: c2x, y: c2y }, { x: px, y: py });
  },
  closePath() {},
};
jGlyph.path.toFunction()(collector as unknown as CanvasRenderingContext2D);
if (current.length) contours.push(current);

const tittle = contours.find((c) => c.every((p) => p.y > xHeight));
if (!tittle) throw new Error("No tittle contour found on j");
const tMinX = Math.min(...tittle.map((p) => p.x));
const tMaxX = Math.max(...tittle.map((p) => p.x));
const tMinY = Math.min(...tittle.map((p) => p.y));
const tMaxY = Math.max(...tittle.map((p) => p.y));

const dotCx = (jx + (tMinX + tMaxX) / 2) * scale;
const dotCy = ascent - ((tMinY + tMaxY) / 2) * scale;
const dotR = (((tMaxX - tMinX) / 2 + (tMaxY - tMinY) / 2) / 2) * scale;

const out = {
  note: "Generated by scripts/generate-wordmark.ts. Do not hand-edit paths.",
  font: "Fraunces variable (OFL 1.1), instance wght=600 opsz=144 SOFT=0 WONK=0",
  width: +width.toFixed(2),
  height: +height.toFixed(2),
  baseline: +ascent.toFixed(2),
  paths: pieces,
  emberDot: {
    cx: +dotCx.toFixed(2),
    cy: +dotCy.toFixed(2),
    r: +dotR.toFixed(2),
  },
};

writeFileSync(
  path.join(process.cwd(), "src", "components", "brand", "logo", "wordmark-data.json"),
  JSON.stringify(out, null, 2),
);
console.log("wordmark written", out.width, out.height, "dot cx", out.emberDot.cx);
