/**
 * Typesets the OG tagline in Instrument Sans (OFL) and writes SVG path
 * data, so social images render with zero runtime font dependencies.
 *
 * Run: npx tsx scripts/generate-tagline.ts
 * Requires: .brand-src/InstrumentSans-var.ttf (gitignored source asset)
 */
import * as fontkit from "fontkit";
import { writeFileSync } from "node:fs";
import path from "node:path";

const fontPath = path.join(
  process.cwd(),
  ".brand-src",
  "InstrumentSans-var.ttf",
);
const loaded = fontkit.openSync(fontPath);
const base = (
  "fonts" in loaded ? (loaded as fontkit.FontCollection).fonts[0] : loaded
) as fontkit.Font;
const font = base.getVariation({ wght: 500, wdth: 100 });

const text = "Know when your software gets too hot.";
const run = font.layout(text);
const scale = 100 / font.unitsPerEm;
const ascent = font.ascent * scale;
const descent = font.descent * scale;

let x = 0;
const parts: string[] = [];
for (let i = 0; i < run.glyphs.length; i++) {
  const glyph = run.glyphs[i];
  const pos = run.positions[i];
  const dx = (x + pos.xOffset) * scale;
  const cmds: string[] = [];
  const fx = (v: number) => +(v * scale + dx).toFixed(2);
  const fy = (v: number) => +(ascent - v * scale).toFixed(2);
  glyph.path.toFunction()({
    moveTo: (px: number, py: number) => cmds.push(`M${fx(px)} ${fy(py)}`),
    lineTo: (px: number, py: number) => cmds.push(`L${fx(px)} ${fy(py)}`),
    quadraticCurveTo: (cx: number, cy: number, px: number, py: number) =>
      cmds.push(`Q${fx(cx)} ${fy(cy)} ${fx(px)} ${fy(py)}`),
    bezierCurveTo: (
      c1x: number,
      c1y: number,
      c2x: number,
      c2y: number,
      px: number,
      py: number,
    ) =>
      cmds.push(
        `C${fx(c1x)} ${fy(c1y)} ${fx(c2x)} ${fy(c2y)} ${fx(px)} ${fy(py)}`,
      ),
    closePath: () => cmds.push("Z"),
  } as unknown as CanvasRenderingContext2D);
  if (cmds.length) parts.push(cmds.join(""));
  x += pos.xAdvance;
}

const out = {
  note: "Generated by scripts/generate-tagline.ts. Do not hand-edit.",
  font: "Instrument Sans variable (OFL 1.1), instance wght=500",
  text,
  width: +(x * scale).toFixed(2),
  height: +(ascent - descent).toFixed(2),
  paths: parts,
};

writeFileSync(
  path.join(process.cwd(), "src", "components", "brand", "logo", "tagline-data.json"),
  JSON.stringify(out, null, 2),
);
console.log("tagline written", out.width, out.height);
