/**
 * Typed analytics definitions registry. Single source of truth for dashboards,
 * reports, exports, and acquisition diligence. Do not redefine metrics in prose.
 */

export type MetricCategory =
  | "growth"
  | "revenue"
  | "retention"
  | "product"
  | "operations"
  | "customer"
  | "support"
  | "affiliate"
  | "content"
  | "security"
  | "infrastructure";

export type DataCompleteness =
  | "complete"
  | "partial"
  | "delayed"
  | "rebuilding"
  | "unavailable"
  | "reconciliating"
  | "stale";

export interface MetricDefinition {
  metricKey: string;
  name: string;
  description: string;
  category: MetricCategory;
  calculation: string;
  sourceTables: string[];
  sourceEvents: string[];
  eligibleRecords: string;
  excludedRecords: string;
  timeBasis: "occurred_at" | "effective_date" | "recorded_at" | "period";
  timezone: "platform" | "utc";
  currency?: "usd" | null;
  aggregation: "sum" | "count" | "rate" | "avg" | "snapshot" | "cohort";
  calculationVersion: string;
  owner: string;
  reviewers: string[];
  lastReviewedAt: string;
  /** Cash vs booked recurring. Never mix without labeling. */
  basis?: "cash" | "recurring" | "count" | "rate" | "state";
}

export const METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  mrr: {
    metricKey: "mrr",
    name: "MRR",
    description:
      "Monthly recurring revenue from active and cancellation-scheduled subscriptions, derived from Stripe recurring price amounts.",
    category: "revenue",
    calculation:
      "Sum of subscriptionMrrCents for statuses in {active, cancellation_scheduled, past_due, grace_period}. Annual amounts / 12.",
    sourceTables: ["billing_subscriptions"],
    sourceEvents: ["billing.subscription.updated"],
    eligibleRecords: "Non-internal organizations with paying subscription statuses",
    excludedRecords: "Trials, incomplete, unpaid, test-mode when live reporting, internal orgs",
    timeBasis: "period",
    timezone: "platform",
    currency: "usd",
    aggregation: "snapshot",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "recurring",
  },
  arr: {
    metricKey: "arr",
    name: "ARR",
    description: "Annualized recurring revenue: MRR × 12.",
    category: "revenue",
    calculation: "mrr * 12",
    sourceTables: ["billing_subscriptions"],
    sourceEvents: ["billing.subscription.updated"],
    eligibleRecords: "Same as MRR",
    excludedRecords: "Same as MRR",
    timeBasis: "period",
    timezone: "platform",
    currency: "usd",
    aggregation: "snapshot",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "recurring",
  },
  gross_collected_revenue: {
    metricKey: "gross_collected_revenue",
    name: "Gross collected revenue",
    description:
      "Cash successfully collected in the period from verified payment events. Not profit.",
    category: "revenue",
    calculation: "Sum of successful payment amounts in billing_payment_events",
    sourceTables: ["billing_payment_events"],
    sourceEvents: ["billing.payment.succeeded"],
    eligibleRecords: "Succeeded payments in range",
    excludedRecords: "Failed payments, test-mode in live reports, refunds (net is separate)",
    timeBasis: "occurred_at",
    timezone: "utc",
    currency: "usd",
    aggregation: "sum",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "cash",
  },
  net_collected_revenue: {
    metricKey: "net_collected_revenue",
    name: "Net collected revenue",
    description: "Gross collected revenue minus refunds in the period. Not profit.",
    category: "revenue",
    calculation: "gross_collected_revenue - refunds",
    sourceTables: ["billing_payment_events"],
    sourceEvents: ["billing.payment.succeeded", "billing.refund.created"],
    eligibleRecords: "Succeeded payments and refunds in range",
    excludedRecords: "Disputes pending, test-mode",
    timeBasis: "occurred_at",
    timezone: "utc",
    currency: "usd",
    aggregation: "sum",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "cash",
  },
  new_mrr: {
    metricKey: "new_mrr",
    name: "New MRR",
    description: "MRR from new paying subscriptions in the period.",
    category: "revenue",
    calculation: "Sum of platform_mrr_movements where movement_type = new",
    sourceTables: ["platform_mrr_movements"],
    sourceEvents: ["billing.subscription.created"],
    eligibleRecords: "New movements in range",
    excludedRecords: "Corrections, internal orgs",
    timeBasis: "effective_date",
    timezone: "platform",
    currency: "usd",
    aggregation: "sum",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "recurring",
  },
  expansion_mrr: {
    metricKey: "expansion_mrr",
    name: "Expansion MRR",
    description: "Positive MRR change from upgrades or seat/plan expansion.",
    category: "revenue",
    calculation: "Sum of positive expansion movements",
    sourceTables: ["platform_mrr_movements"],
    sourceEvents: ["billing.subscription.updated"],
    eligibleRecords: "movement_type = expansion",
    excludedRecords: "Internal orgs",
    timeBasis: "effective_date",
    timezone: "platform",
    currency: "usd",
    aggregation: "sum",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "recurring",
  },
  contraction_mrr: {
    metricKey: "contraction_mrr",
    name: "Contraction MRR",
    description: "Negative MRR change from downgrades (not full churn).",
    category: "revenue",
    calculation: "Sum of absolute contraction movements",
    sourceTables: ["platform_mrr_movements"],
    sourceEvents: ["billing.subscription.updated"],
    eligibleRecords: "movement_type = contraction",
    excludedRecords: "Internal orgs",
    timeBasis: "effective_date",
    timezone: "platform",
    currency: "usd",
    aggregation: "sum",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "recurring",
  },
  churned_mrr: {
    metricKey: "churned_mrr",
    name: "Churned MRR",
    description: "MRR lost to cancellations that took effect in the period.",
    category: "revenue",
    calculation: "Sum of churn movements",
    sourceTables: ["platform_mrr_movements"],
    sourceEvents: ["billing.subscription.canceled"],
    eligibleRecords: "movement_type = churn",
    excludedRecords: "Internal orgs",
    timeBasis: "effective_date",
    timezone: "platform",
    currency: "usd",
    aggregation: "sum",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "recurring",
  },
  reactivation_mrr: {
    metricKey: "reactivation_mrr",
    name: "Reactivation MRR",
    description: "MRR regained from previously churned organizations.",
    category: "revenue",
    calculation: "Sum of reactivation movements",
    sourceTables: ["platform_mrr_movements"],
    sourceEvents: ["billing.subscription.reactivated"],
    eligibleRecords: "movement_type = reactivation",
    excludedRecords: "Internal orgs",
    timeBasis: "effective_date",
    timezone: "platform",
    currency: "usd",
    aggregation: "sum",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "recurring",
  },
  logo_churn: {
    metricKey: "logo_churn",
    name: "Logo churn",
    description: "Share of paying organizations that canceled in the period.",
    category: "retention",
    calculation: "Canceled paying orgs / starting paying orgs",
    sourceTables: ["billing_subscriptions", "billing_cancellation_records"],
    sourceEvents: ["billing.subscription.canceled"],
    eligibleRecords: "Paying orgs at period start",
    excludedRecords: "Internal orgs, never-paid",
    timeBasis: "period",
    timezone: "platform",
    currency: null,
    aggregation: "rate",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "rate",
  },
  revenue_churn: {
    metricKey: "revenue_churn",
    name: "Revenue churn",
    description: "Churned MRR / starting MRR.",
    category: "retention",
    calculation: "churned_mrr / starting_mrr",
    sourceTables: ["platform_mrr_movements"],
    sourceEvents: ["billing.subscription.canceled"],
    eligibleRecords: "Period movements",
    excludedRecords: "Internal orgs",
    timeBasis: "period",
    timezone: "platform",
    currency: null,
    aggregation: "rate",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "rate",
  },
  net_revenue_retention: {
    metricKey: "net_revenue_retention",
    name: "Net revenue retention",
    description:
      "(Starting MRR + expansion + reactivation - contraction - churn) / starting MRR.",
    category: "retention",
    calculation: "NRR formula over cohort starting MRR",
    sourceTables: ["platform_mrr_movements"],
    sourceEvents: [],
    eligibleRecords: "Organizations paying at cohort start",
    excludedRecords: "Internal orgs",
    timeBasis: "period",
    timezone: "platform",
    currency: null,
    aggregation: "rate",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "rate",
  },
  gross_revenue_retention: {
    metricKey: "gross_revenue_retention",
    name: "Gross revenue retention",
    description: "(Starting MRR - contraction - churn) / starting MRR. No expansion credit.",
    category: "retention",
    calculation: "GRR formula",
    sourceTables: ["platform_mrr_movements"],
    sourceEvents: [],
    eligibleRecords: "Organizations paying at cohort start",
    excludedRecords: "Internal orgs",
    timeBasis: "period",
    timezone: "platform",
    currency: null,
    aggregation: "rate",
    calculationVersion: "1",
    owner: "billing_operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "rate",
  },
  activated_organizations: {
    metricKey: "activated_organizations",
    name: "Activated organizations",
    description:
      "Organizations that reached full activation (monitor active + alert path + meaningful first value). Signup is not activation.",
    category: "growth",
    calculation: "Count of orgs with lifecycle state in activated set",
    sourceTables: ["lifecycle_states"],
    sourceEvents: ["onboarding.activated"],
    eligibleRecords: "Non-internal organizations",
    excludedRecords: "Internal orgs, fixtures",
    timeBasis: "period",
    timezone: "platform",
    currency: null,
    aggregation: "count",
    calculationVersion: "1",
    owner: "operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "count",
  },
  active_monitors: {
    metricKey: "active_monitors",
    name: "Active monitors",
    description: "Monitors currently enabled for scheduling.",
    category: "product",
    calculation: "Count monitors where status = active",
    sourceTables: ["monitors"],
    sourceEvents: [],
    eligibleRecords: "Active monitors for non-internal orgs",
    excludedRecords: "Paused, deleted, internal fixtures",
    timeBasis: "period",
    timezone: "utc",
    currency: null,
    aggregation: "snapshot",
    calculationVersion: "1",
    owner: "operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "state",
  },
  check_success_rate: {
    metricKey: "check_success_rate",
    name: "Check success rate",
    description: "Successful check executions / completed check executions.",
    category: "product",
    calculation: "successes / completed from aggregates",
    sourceTables: ["platform_daily_health", "check_results"],
    sourceEvents: ["monitoring.check.completed"],
    eligibleRecords: "Completed checks in range",
    excludedRecords: "Cancelled leases, operator replays labeled separately",
    timeBasis: "occurred_at",
    timezone: "utc",
    currency: null,
    aggregation: "rate",
    calculationVersion: "1",
    owner: "operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "rate",
  },
  alert_delivery_success_rate: {
    metricKey: "alert_delivery_success_rate",
    name: "Alert delivery success rate",
    description: "Successful alert deliveries / attempted deliveries.",
    category: "operations",
    calculation: "delivered / attempted from alert delivery aggregates",
    sourceTables: ["alert_deliveries"],
    sourceEvents: ["alerts.delivery.succeeded", "alerts.delivery.failed"],
    eligibleRecords: "Delivery attempts in range",
    excludedRecords: "Quiet-hour suppressions (reported separately)",
    timeBasis: "occurred_at",
    timezone: "utc",
    currency: null,
    aggregation: "rate",
    calculationVersion: "1",
    owner: "operations",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "rate",
  },
  approval_backlog: {
    metricKey: "approval_backlog",
    name: "Approval backlog",
    description: "Approvals in submitted or under_review state.",
    category: "operations",
    calculation: "Count platform_approvals where state in (submitted, under_review)",
    sourceTables: ["platform_approvals"],
    sourceEvents: [],
    eligibleRecords: "Open approvals",
    excludedRecords: "Draft, expired, completed",
    timeBasis: "period",
    timezone: "platform",
    currency: null,
    aggregation: "snapshot",
    calculationVersion: "1",
    owner: "platform_owner",
    reviewers: ["auditor"],
    lastReviewedAt: "2026-07-17",
    basis: "state",
  },
  critical_security_events: {
    metricKey: "critical_security_events",
    name: "Critical security events",
    description: "Unresolved critical security events.",
    category: "security",
    calculation: "Count where severity = critical and status not terminal",
    sourceTables: ["platform_security_events"],
    sourceEvents: ["security.event.detected"],
    eligibleRecords: "Open critical events",
    excludedRecords: "False positives, resolved",
    timeBasis: "period",
    timezone: "utc",
    currency: null,
    aggregation: "snapshot",
    calculationVersion: "1",
    owner: "security",
    reviewers: ["platform_owner"],
    lastReviewedAt: "2026-07-17",
    basis: "state",
  },
};

export function getMetricDefinition(key: string): MetricDefinition | null {
  return METRIC_DEFINITIONS[key] ?? null;
}

export function listMetricDefinitions(
  category?: MetricCategory,
): MetricDefinition[] {
  const all = Object.values(METRIC_DEFINITIONS);
  return category ? all.filter((m) => m.category === category) : all;
}
