/**
 * Typed operational event registry. Payloads are bounded; no secrets or
 * customer content in analytics events.
 */

export const OPERATIONAL_EVENT_TYPES = [
  "auth.session.created",
  "org.created",
  "org.activated",
  "monitor.created",
  "monitor.activated",
  "check.completed",
  "check.delayed",
  "incident.opened",
  "incident.resolved",
  "alert.delivered",
  "alert.failed",
  "status_page.published",
  "status_page.stale",
  "subscriber.confirmed",
  "subscriber.bounced",
  "billing.subscription.created",
  "billing.subscription.updated",
  "billing.payment.succeeded",
  "billing.payment.failed",
  "billing.refund.created",
  "lifecycle.message.sent",
  "affiliate.conversion.confirmed",
  "affiliate.payout.blocked",
  "support.handoff.opened",
  "support.gap.recorded",
  "content.published",
  "security.event.detected",
  "privacy.request.received",
  "deployment.completed",
  "feature_flag.changed",
  "provider.degraded",
  "reconciliation.difference",
  "approval.submitted",
  "anomaly.detected",
] as const;

export type OperationalEventType = (typeof OPERATIONAL_EVENT_TYPES)[number];

export interface OperationalEventDefinition {
  type: OperationalEventType;
  version: number;
  sourceSystem: string;
  description: string;
  allowedMetadataKeys: string[];
}

export const OPERATIONAL_EVENT_REGISTRY: Record<
  OperationalEventType,
  OperationalEventDefinition
> = {
  "auth.session.created": {
    type: "auth.session.created",
    version: 1,
    sourceSystem: "clerk",
    description: "Authenticated session established",
    allowedMetadataKeys: ["provider"],
  },
  "org.created": {
    type: "org.created",
    version: 1,
    sourceSystem: "app",
    description: "Organization created",
    allowedMetadataKeys: ["plan_key"],
  },
  "org.activated": {
    type: "org.activated",
    version: 1,
    sourceSystem: "lifecycle",
    description: "Organization reached activation",
    allowedMetadataKeys: ["activation_version"],
  },
  "monitor.created": {
    type: "monitor.created",
    version: 1,
    sourceSystem: "monitoring",
    description: "Monitor created",
    allowedMetadataKeys: ["monitor_type", "interval_seconds"],
  },
  "monitor.activated": {
    type: "monitor.activated",
    version: 1,
    sourceSystem: "monitoring",
    description: "Monitor began scheduling",
    allowedMetadataKeys: ["monitor_type"],
  },
  "check.completed": {
    type: "check.completed",
    version: 1,
    sourceSystem: "monitoring",
    description: "Check execution completed",
    allowedMetadataKeys: ["result_category", "region", "latency_ms"],
  },
  "check.delayed": {
    type: "check.delayed",
    version: 1,
    sourceSystem: "monitoring",
    description: "Check overdue relative to schedule",
    allowedMetadataKeys: ["delay_seconds", "region"],
  },
  "incident.opened": {
    type: "incident.opened",
    version: 1,
    sourceSystem: "incidents",
    description: "Customer incident opened",
    allowedMetadataKeys: ["severity", "origin"],
  },
  "incident.resolved": {
    type: "incident.resolved",
    version: 1,
    sourceSystem: "incidents",
    description: "Customer incident resolved",
    allowedMetadataKeys: ["duration_seconds"],
  },
  "alert.delivered": {
    type: "alert.delivered",
    version: 1,
    sourceSystem: "alerts",
    description: "Alert delivery succeeded",
    allowedMetadataKeys: ["channel", "provider", "latency_ms"],
  },
  "alert.failed": {
    type: "alert.failed",
    version: 1,
    sourceSystem: "alerts",
    description: "Alert delivery failed",
    allowedMetadataKeys: ["channel", "provider", "failure_category"],
  },
  "status_page.published": {
    type: "status_page.published",
    version: 1,
    sourceSystem: "status_pages",
    description: "Status page published",
    allowedMetadataKeys: ["theme"],
  },
  "status_page.stale": {
    type: "status_page.stale",
    version: 1,
    sourceSystem: "status_pages",
    description: "Status page projection stale",
    allowedMetadataKeys: ["staleness_seconds"],
  },
  "subscriber.confirmed": {
    type: "subscriber.confirmed",
    version: 1,
    sourceSystem: "subscribers",
    description: "Subscriber confirmed (aggregate-safe)",
    allowedMetadataKeys: ["status_page_id"],
  },
  "subscriber.bounced": {
    type: "subscriber.bounced",
    version: 1,
    sourceSystem: "subscribers",
    description: "Subscriber email bounced",
    allowedMetadataKeys: ["bounce_class"],
  },
  "billing.subscription.created": {
    type: "billing.subscription.created",
    version: 1,
    sourceSystem: "billing",
    description: "Subscription created",
    allowedMetadataKeys: ["plan_key", "interval", "mrr_cents"],
  },
  "billing.subscription.updated": {
    type: "billing.subscription.updated",
    version: 1,
    sourceSystem: "billing",
    description: "Subscription updated",
    allowedMetadataKeys: ["plan_key", "status", "mrr_cents"],
  },
  "billing.payment.succeeded": {
    type: "billing.payment.succeeded",
    version: 1,
    sourceSystem: "billing",
    description: "Payment collected",
    allowedMetadataKeys: ["amount_cents", "currency"],
  },
  "billing.payment.failed": {
    type: "billing.payment.failed",
    version: 1,
    sourceSystem: "billing",
    description: "Payment failed",
    allowedMetadataKeys: ["failure_category"],
  },
  "billing.refund.created": {
    type: "billing.refund.created",
    version: 1,
    sourceSystem: "billing",
    description: "Refund created",
    allowedMetadataKeys: ["amount_cents"],
  },
  "lifecycle.message.sent": {
    type: "lifecycle.message.sent",
    version: 1,
    sourceSystem: "lifecycle",
    description: "Lifecycle message sent",
    allowedMetadataKeys: ["message_key"],
  },
  "affiliate.conversion.confirmed": {
    type: "affiliate.conversion.confirmed",
    version: 1,
    sourceSystem: "affiliates",
    description: "Affiliate conversion confirmed",
    allowedMetadataKeys: ["affiliate_id", "mrr_cents"],
  },
  "affiliate.payout.blocked": {
    type: "affiliate.payout.blocked",
    version: 1,
    sourceSystem: "affiliates",
    description: "Affiliate payout blocked",
    allowedMetadataKeys: ["block_reason"],
  },
  "support.handoff.opened": {
    type: "support.handoff.opened",
    version: 1,
    sourceSystem: "support",
    description: "Support handoff opened",
    allowedMetadataKeys: ["intent", "product_area"],
  },
  "support.gap.recorded": {
    type: "support.gap.recorded",
    version: 1,
    sourceSystem: "support",
    description: "Documentation or product gap recorded",
    allowedMetadataKeys: ["gap_type", "product_area"],
  },
  "content.published": {
    type: "content.published",
    version: 1,
    sourceSystem: "content",
    description: "Content published",
    allowedMetadataKeys: ["content_type", "slug"],
  },
  "security.event.detected": {
    type: "security.event.detected",
    version: 1,
    sourceSystem: "security",
    description: "Security event detected",
    allowedMetadataKeys: ["severity", "event_type"],
  },
  "privacy.request.received": {
    type: "privacy.request.received",
    version: 1,
    sourceSystem: "privacy",
    description: "Privacy request received",
    allowedMetadataKeys: ["request_type"],
  },
  "deployment.completed": {
    type: "deployment.completed",
    version: 1,
    sourceSystem: "releases",
    description: "Deployment completed",
    allowedMetadataKeys: ["environment", "version"],
  },
  "feature_flag.changed": {
    type: "feature_flag.changed",
    version: 1,
    sourceSystem: "feature_flags",
    description: "Feature flag changed",
    allowedMetadataKeys: ["flag_key", "change_type"],
  },
  "provider.degraded": {
    type: "provider.degraded",
    version: 1,
    sourceSystem: "providers",
    description: "Provider health degraded",
    allowedMetadataKeys: ["provider_key", "state"],
  },
  "reconciliation.difference": {
    type: "reconciliation.difference",
    version: 1,
    sourceSystem: "reconciliation",
    description: "Reconciliation difference found",
    allowedMetadataKeys: ["domain", "difference_count"],
  },
  "approval.submitted": {
    type: "approval.submitted",
    version: 1,
    sourceSystem: "approvals",
    description: "Approval submitted",
    allowedMetadataKeys: ["approval_type", "risk"],
  },
  "anomaly.detected": {
    type: "anomaly.detected",
    version: 1,
    sourceSystem: "anomalies",
    description: "Anomaly rule fired",
    allowedMetadataKeys: ["rule_key", "severity"],
  },
};
